workflow_dispatch:
     inputs:
      teamName:
        type: choice
        description: "Supported Teams"
        required: true
        default: 'HackRockAthon'
        options:
              - HackRockAThon
              - HeWasNumber1
              - AccountingSucks
      xmlTestSuite:
         type: filterChoice
         description: 'XML Test Suite'
         required: true
         default: ''
         dependsOn: teamName
         options:
                options: HackRockAThon
                    - SQLInjection.xml
                    - BlackBox.xml
                 options: HeWasNumber1
                    - smoke.xml
                    - regression.xml
                    - sanity.xml
                 options: AccountingSucks
                    - InvoiceChecks.xml
                    - PricingChecks.xml
